# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Par un ap R
email: didzis.elferts [at] lu.lv
description: > # this means to ignore newlines until "baseurl:"
  R jaunumi, R paketes un padomi, manas domas par R un statistiku.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://delferts.github.io" # the base hostname & protocol for your site
twitter_username: delferts
github_username:  delferts

# Build settings
markdown: kramdown

# Analitics settings
analytics :
  provider : google
  google : 
      tracking_id : 'UA-74266818-1'
  getclicky :
    site_id :
