<!DOCTYPE html>
<html >

<head>

  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Praktiskā biometrija</title>
  <meta content="text/html; charset=UTF-8" http-equiv="Content-Type">
  <meta name="description" content="Piemēri darbā ar programmu R, lai risinātu statistikas problēmas bioloģijā.">
  <meta name="generator" content="bookdown 0.0.60 and GitBook 2.6.7">

  <meta property="og:title" content="Praktiskā biometrija" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="Piemēri darbā ar programmu R, lai risinātu statistikas problēmas bioloģijā." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Praktiskā biometrija" />
  
  <meta name="twitter:description" content="Piemēri darbā ar programmu R, lai risinātu statistikas problēmas bioloģijā." />
  

<meta name="author" content="Didzis Elferts">

<meta name="date" content="2016-04-06">

<script type="text/x-mathjax-config">
MathJax.Hub.Config({
  TeX: { equationNumbers: { autoNumber: "AMS" } }
});
</script>
  <script src="https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML" type="text/javascript"></script>

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  
  
<link rel="prev" href="paraugkopu-salidzinasana.html">
<link rel="next" href="korelacijas-analize.html">

<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />









<style type="text/css">
div.sourceCode { overflow-x: auto; }
table.sourceCode, tr.sourceCode, td.lineNumbers, td.sourceCode {
  margin: 0; padding: 0; vertical-align: baseline; border: none; }
table.sourceCode { width: 100%; line-height: 100%; }
td.lineNumbers { text-align: right; padding-right: 4px; padding-left: 4px; color: #aaaaaa; border-right: 1px solid #aaaaaa; }
td.sourceCode { padding-left: 5px; }
code > span.kw { color: #007020; font-weight: bold; } /* Keyword */
code > span.dt { color: #902000; } /* DataType */
code > span.dv { color: #40a070; } /* DecVal */
code > span.bn { color: #40a070; } /* BaseN */
code > span.fl { color: #40a070; } /* Float */
code > span.ch { color: #4070a0; } /* Char */
code > span.st { color: #4070a0; } /* String */
code > span.co { color: #60a0b0; font-style: italic; } /* Comment */
code > span.ot { color: #007020; } /* Other */
code > span.al { color: #ff0000; font-weight: bold; } /* Alert */
code > span.fu { color: #06287e; } /* Function */
code > span.er { color: #ff0000; font-weight: bold; } /* Error */
code > span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
code > span.cn { color: #880000; } /* Constant */
code > span.sc { color: #4070a0; } /* SpecialChar */
code > span.vs { color: #4070a0; } /* VerbatimString */
code > span.ss { color: #bb6688; } /* SpecialString */
code > span.im { } /* Import */
code > span.va { color: #19177c; } /* Variable */
code > span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code > span.op { color: #666666; } /* Operator */
code > span.bu { } /* BuiltIn */
code > span.ex { } /* Extension */
code > span.pp { color: #bc7a00; } /* Preprocessor */
code > span.at { color: #7d9029; } /* Attribute */
code > span.do { color: #ba2121; font-style: italic; } /* Documentation */
code > span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code > span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code > span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>


  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><p>Praktiskā biometrija</p></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Ievads</a></li>
<li class="chapter" data-level="2" data-path="biometrija-un-datu-analize.html"><a href="biometrija-un-datu-analize.html"><i class="fa fa-check"></i><b>2</b> Biometrija un datu analīze</a><ul>
<li class="chapter" data-level="2.1" data-path="biometrija-un-datu-analize.html"><a href="biometrija-un-datu-analize.html#kas-ir-biometrija"><i class="fa fa-check"></i><b>2.1</b> Kas ir biometrija?</a></li>
<li class="chapter" data-level="2.2" data-path="biometrija-un-datu-analize.html"><a href="biometrija-un-datu-analize.html#paraugkopa-un-generalkopa"><i class="fa fa-check"></i><b>2.2</b> Paraugkopa un ģenerālkopa</a></li>
<li class="chapter" data-level="2.3" data-path="biometrija-un-datu-analize.html"><a href="biometrija-un-datu-analize.html#hipotezu-parbaude"><i class="fa fa-check"></i><b>2.3</b> Hipotēžu pārbaude</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="ievads-darba-ar-programmu-r.html"><a href="ievads-darba-ar-programmu-r.html"><i class="fa fa-check"></i><b>3</b> Ievads darbā ar programmu R</a><ul>
<li class="chapter" data-level="3.1" data-path="ievads-darba-ar-programmu-r.html"><a href="ievads-darba-ar-programmu-r.html#kas-ir-programma-r-un-ka-uzsakt-darbu"><i class="fa fa-check"></i><b>3.1</b> Kas ir programma R un kā uzsākt darbu?</a><ul>
<li class="chapter" data-level="3.1.1" data-path="ievads-darba-ar-programmu-r.html"><a href="ievads-darba-ar-programmu-r.html#r-vide"><i class="fa fa-check"></i><b>3.1.1</b> R vide</a></li>
<li class="chapter" data-level="3.1.2" data-path="ievads-darba-ar-programmu-r.html"><a href="ievads-darba-ar-programmu-r.html#r-instalacija-un-papildus-paketes"><i class="fa fa-check"></i><b>3.1.2</b> R instalācija un papildus paketes</a></li>
<li class="chapter" data-level="3.1.3" data-path="ievads-darba-ar-programmu-r.html"><a href="ievads-darba-ar-programmu-r.html#palidzibas-iegusana"><i class="fa fa-check"></i><b>3.1.3</b> Palīdzības iegūšana</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="ievads-darba-ar-programmu-r.html"><a href="ievads-darba-ar-programmu-r.html#darbs-ar-r"><i class="fa fa-check"></i><b>3.2</b> Darbs ar R</a><ul>
<li class="chapter" data-level="3.2.1" data-path="ievads-darba-ar-programmu-r.html"><a href="ievads-darba-ar-programmu-r.html#komandu-veidosana"><i class="fa fa-check"></i><b>3.2.1</b> Komandu veidošana</a></li>
<li class="chapter" data-level="3.2.2" data-path="ievads-darba-ar-programmu-r.html"><a href="ievads-darba-ar-programmu-r.html#kalkulators"><i class="fa fa-check"></i><b>3.2.2</b> Kalkulators</a></li>
<li class="chapter" data-level="3.2.3" data-path="ievads-darba-ar-programmu-r.html"><a href="ievads-darba-ar-programmu-r.html#datu-veidi"><i class="fa fa-check"></i><b>3.2.3</b> Datu veidi</a></li>
<li class="chapter" data-level="3.2.4" data-path="ievads-darba-ar-programmu-r.html"><a href="ievads-darba-ar-programmu-r.html#datu-strukturas"><i class="fa fa-check"></i><b>3.2.4</b> Datu struktūras</a></li>
<li class="chapter" data-level="3.2.5" data-path="ievads-darba-ar-programmu-r.html"><a href="ievads-darba-ar-programmu-r.html#datu-importesana"><i class="fa fa-check"></i><b>3.2.5</b> Datu importēšana</a></li>
<li class="chapter" data-level="3.2.6" data-path="ievads-darba-ar-programmu-r.html"><a href="ievads-darba-ar-programmu-r.html#datu-eksportesana"><i class="fa fa-check"></i><b>3.2.6</b> Datu eksportēšana</a></li>
<li class="chapter" data-level="3.2.7" data-path="ievads-darba-ar-programmu-r.html"><a href="ievads-darba-ar-programmu-r.html#darbs-ar-datiem"><i class="fa fa-check"></i><b>3.2.7</b> Darbs ar datiem</a></li>
<li class="chapter" data-level="3.2.8" data-path="ievads-darba-ar-programmu-r.html"><a href="ievads-darba-ar-programmu-r.html#darba-vides-sakartosana"><i class="fa fa-check"></i><b>3.2.8</b> Darba vides sakārtošana</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="grafiskas-iespejas-programma-r.html"><a href="grafiskas-iespejas-programma-r.html"><i class="fa fa-check"></i><b>4</b> Grafiskās iespējas programmā R</a><ul>
<li class="chapter" data-level="4.1" data-path="grafiskas-iespejas-programma-r.html"><a href="grafiskas-iespejas-programma-r.html#pamatgrafiki"><i class="fa fa-check"></i><b>4.1</b> Pamatgrafiki</a><ul>
<li class="chapter" data-level="4.1.1" data-path="grafiskas-iespejas-programma-r.html"><a href="grafiskas-iespejas-programma-r.html#plot"><i class="fa fa-check"></i><b>4.1.1</b> plot()</a></li>
<li class="chapter" data-level="4.1.2" data-path="grafiskas-iespejas-programma-r.html"><a href="grafiskas-iespejas-programma-r.html#boxplot"><i class="fa fa-check"></i><b>4.1.2</b> boxplot()</a></li>
<li class="chapter" data-level="4.1.3" data-path="grafiskas-iespejas-programma-r.html"><a href="grafiskas-iespejas-programma-r.html#hist"><i class="fa fa-check"></i><b>4.1.3</b> hist()</a></li>
<li class="chapter" data-level="4.1.4" data-path="grafiskas-iespejas-programma-r.html"><a href="grafiskas-iespejas-programma-r.html#barplot"><i class="fa fa-check"></i><b>4.1.4</b> barplot()</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="grafiskas-iespejas-programma-r.html"><a href="grafiskas-iespejas-programma-r.html#dati-grafiku-veidosanai"><i class="fa fa-check"></i><b>4.2</b> Dati grafiku veidošanai</a></li>
<li class="chapter" data-level="4.3" data-path="grafiskas-iespejas-programma-r.html"><a href="grafiskas-iespejas-programma-r.html#grafiku-parametru-noteiksana"><i class="fa fa-check"></i><b>4.3</b> Grafiku parametru noteikšana</a><ul>
<li class="chapter" data-level="4.3.1" data-path="grafiskas-iespejas-programma-r.html"><a href="grafiskas-iespejas-programma-r.html#grafiku-izvietojums-lapa"><i class="fa fa-check"></i><b>4.3.1</b> Grafiku izvietojums lapā</a></li>
<li class="chapter" data-level="4.3.2" data-path="grafiskas-iespejas-programma-r.html"><a href="grafiskas-iespejas-programma-r.html#plot-grafiku-tipi"><i class="fa fa-check"></i><b>4.3.2</b> plot() grafiku tipi</a></li>
<li class="chapter" data-level="4.3.3" data-path="grafiskas-iespejas-programma-r.html"><a href="grafiskas-iespejas-programma-r.html#liniju-parametri"><i class="fa fa-check"></i><b>4.3.3</b> Līniju parametri</a></li>
<li class="chapter" data-level="4.3.4" data-path="grafiskas-iespejas-programma-r.html"><a href="grafiskas-iespejas-programma-r.html#simbolu-veidi"><i class="fa fa-check"></i><b>4.3.4</b> Simbolu veidi</a></li>
<li class="chapter" data-level="4.3.5" data-path="grafiskas-iespejas-programma-r.html"><a href="grafiskas-iespejas-programma-r.html#virsraksti-un-teksti-pie-asim"><i class="fa fa-check"></i><b>4.3.5</b> Virsraksti un teksti pie asīm</a></li>
<li class="chapter" data-level="4.3.6" data-path="grafiskas-iespejas-programma-r.html"><a href="grafiskas-iespejas-programma-r.html#teksts-grafika-ieksiene"><i class="fa fa-check"></i><b>4.3.6</b> Teksts grafika iekšienē</a></li>
<li class="chapter" data-level="4.3.7" data-path="grafiskas-iespejas-programma-r.html"><a href="grafiskas-iespejas-programma-r.html#tekstu-parametri"><i class="fa fa-check"></i><b>4.3.7</b> Tekstu parametri</a></li>
<li class="chapter" data-level="4.3.8" data-path="grafiskas-iespejas-programma-r.html"><a href="grafiskas-iespejas-programma-r.html#asis"><i class="fa fa-check"></i><b>4.3.8</b> Asis</a></li>
<li class="chapter" data-level="4.3.9" data-path="grafiskas-iespejas-programma-r.html"><a href="grafiskas-iespejas-programma-r.html#divas-y-asis"><i class="fa fa-check"></i><b>4.3.9</b> Divas y asis</a></li>
<li class="chapter" data-level="4.3.10" data-path="grafiskas-iespejas-programma-r.html"><a href="grafiskas-iespejas-programma-r.html#krasas"><i class="fa fa-check"></i><b>4.3.10</b> Krāsas</a></li>
<li class="chapter" data-level="4.3.11" data-path="grafiskas-iespejas-programma-r.html"><a href="grafiskas-iespejas-programma-r.html#legenda"><i class="fa fa-check"></i><b>4.3.11</b> Leģenda</a></li>
<li class="chapter" data-level="4.3.12" data-path="grafiskas-iespejas-programma-r.html"><a href="grafiskas-iespejas-programma-r.html#linijas-grafikos"><i class="fa fa-check"></i><b>4.3.12</b> Līnijas grafikos</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="grafiskas-iespejas-programma-r.html"><a href="grafiskas-iespejas-programma-r.html#grafiku-saglabasana"><i class="fa fa-check"></i><b>4.4</b> Grafiku saglabāšana</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="datu-izzinasana-un-normalitates-testi.html"><a href="datu-izzinasana-un-normalitates-testi.html"><i class="fa fa-check"></i><b>5</b> Datu izzināšana un normalitātes testi</a><ul>
<li class="chapter" data-level="5.1" data-path="datu-izzinasana-un-normalitates-testi.html"><a href="datu-izzinasana-un-normalitates-testi.html#datu-izzinasana"><i class="fa fa-check"></i><b>5.1</b> Datu izzināšana</a></li>
<li class="chapter" data-level="5.2" data-path="datu-izzinasana-un-normalitates-testi.html"><a href="datu-izzinasana-un-normalitates-testi.html#normalitates-testi"><i class="fa fa-check"></i><b>5.2</b> Normalitātes testi</a><ul>
<li class="chapter" data-level="5.2.1" data-path="datu-izzinasana-un-normalitates-testi.html"><a href="datu-izzinasana-un-normalitates-testi.html#grafiska-analize"><i class="fa fa-check"></i><b>5.2.1</b> Grafiskā analīze</a></li>
<li class="chapter" data-level="5.2.2" data-path="datu-izzinasana-un-normalitates-testi.html"><a href="datu-izzinasana-un-normalitates-testi.html#analitiska-analize"><i class="fa fa-check"></i><b>5.2.2</b> Analītiskā analīze</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="statistiskie-raditaji-un-ticamibas-intervali.html"><a href="statistiskie-raditaji-un-ticamibas-intervali.html"><i class="fa fa-check"></i><b>6</b> Statistiskie rādītāji un ticamības intervāli</a><ul>
<li class="chapter" data-level="6.1" data-path="statistiskie-raditaji-un-ticamibas-intervali.html"><a href="statistiskie-raditaji-un-ticamibas-intervali.html#statistiskie-raditaji"><i class="fa fa-check"></i><b>6.1</b> Statistiskie rādītāji</a><ul>
<li class="chapter" data-level="6.1.1" data-path="statistiskie-raditaji-un-ticamibas-intervali.html"><a href="statistiskie-raditaji-un-ticamibas-intervali.html#teoretiskais-pamatojums"><i class="fa fa-check"></i><b>6.1.1</b> Teorētiskais pamatojums</a></li>
<li class="chapter" data-level="6.1.2" data-path="statistiskie-raditaji-un-ticamibas-intervali.html"><a href="statistiskie-raditaji-un-ticamibas-intervali.html#statistisko-raditaju-aprekinasana-programma-r"><i class="fa fa-check"></i><b>6.1.2</b> Statistisko rādītāju aprēķināšana programmā R</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="statistiskie-raditaji-un-ticamibas-intervali.html"><a href="statistiskie-raditaji-un-ticamibas-intervali.html#ticamibas-intervali"><i class="fa fa-check"></i><b>6.2</b> Ticamības intervāli</a><ul>
<li class="chapter" data-level="6.2.1" data-path="statistiskie-raditaji-un-ticamibas-intervali.html"><a href="statistiskie-raditaji-un-ticamibas-intervali.html#teoretiskais-pamatojums-1"><i class="fa fa-check"></i><b>6.2.1</b> Teorētiskais pamatojums</a></li>
<li class="chapter" data-level="6.2.2" data-path="statistiskie-raditaji-un-ticamibas-intervali.html"><a href="statistiskie-raditaji-un-ticamibas-intervali.html#ticamibas-intervalu-aprekinasana"><i class="fa fa-check"></i><b>6.2.2</b> Ticamības intervālu aprēķināšana</a></li>
<li class="chapter" data-level="6.2.3" data-path="statistiskie-raditaji-un-ticamibas-intervali.html"><a href="statistiskie-raditaji-un-ticamibas-intervali.html#bootstrap-ticamibas-intervali"><i class="fa fa-check"></i><b>6.2.3</b> Bootstrap ticamības intervāli</a></li>
<li class="chapter" data-level="6.2.4" data-path="statistiskie-raditaji-un-ticamibas-intervali.html"><a href="statistiskie-raditaji-un-ticamibas-intervali.html#ticamibas-intervalu-grafiskais-attelojums"><i class="fa fa-check"></i><b>6.2.4</b> Ticamības intervālu grafiskais attēlojums</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="paraugkopu-salidzinasana.html"><a href="paraugkopu-salidzinasana.html"><i class="fa fa-check"></i><b>7</b> Paraugkopu salīdzināšana</a><ul>
<li class="chapter" data-level="7.1" data-path="paraugkopu-salidzinasana.html"><a href="paraugkopu-salidzinasana.html#teoretiskais-pamatojums-2"><i class="fa fa-check"></i><b>7.1</b> Teorētiskais pamatojums</a><ul>
<li class="chapter" data-level="7.1.1" data-path="paraugkopu-salidzinasana.html"><a href="paraugkopu-salidzinasana.html#t-tests"><i class="fa fa-check"></i><b>7.1.1</b> T-tests</a></li>
<li class="chapter" data-level="7.1.2" data-path="paraugkopu-salidzinasana.html"><a href="paraugkopu-salidzinasana.html#dispersiju-salidzinasana"><i class="fa fa-check"></i><b>7.1.2</b> Dispersiju salīdzināšana</a></li>
<li class="chapter" data-level="7.1.3" data-path="paraugkopu-salidzinasana.html"><a href="paraugkopu-salidzinasana.html#wilcoxon-tests-neatkarigiem-noverojumiem"><i class="fa fa-check"></i><b>7.1.3</b> Wilcoxon tests neatkarīgiem novērojumiem</a></li>
<li class="chapter" data-level="7.1.4" data-path="paraugkopu-salidzinasana.html"><a href="paraugkopu-salidzinasana.html#wilcoxon-tests-atkarigiem-noverojumiem"><i class="fa fa-check"></i><b>7.1.4</b> Wilcoxon tests atkarīgiem novērojumiem</a></li>
<li class="chapter" data-level="7.1.5" data-path="paraugkopu-salidzinasana.html"><a href="paraugkopu-salidzinasana.html#chi2-tests"><i class="fa fa-check"></i><b>7.1.5</b> <span class="math inline">\(\chi^2\)</span> tests</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="paraugkopu-salidzinasana.html"><a href="paraugkopu-salidzinasana.html#paraugkopu-salidzinasana-programma-r"><i class="fa fa-check"></i><b>7.2</b> Paraugkopu salīdzināšana programmā R</a><ul>
<li class="chapter" data-level="7.2.1" data-path="paraugkopu-salidzinasana.html"><a href="paraugkopu-salidzinasana.html#datu-sagatavosana"><i class="fa fa-check"></i><b>7.2.1</b> Datu sagatavošana</a></li>
<li class="chapter" data-level="7.2.2" data-path="paraugkopu-salidzinasana.html"><a href="paraugkopu-salidzinasana.html#divu-neatkarigu-paraugkopu-salidzinasana-ar-parametriskajam-metodem"><i class="fa fa-check"></i><b>7.2.2</b> Divu neatkarīgu paraugkopu salīdzināšana ar parametriskajām metodēm</a></li>
<li class="chapter" data-level="7.2.3" data-path="paraugkopu-salidzinasana.html"><a href="paraugkopu-salidzinasana.html#vairaku-neatkarigu-paraugkopu-salidzinasana-ar-parametriskajam-metodem"><i class="fa fa-check"></i><b>7.2.3</b> Vairāku neatkarīgu paraugkopu salīdzināšana ar parametriskajām metodēm</a></li>
<li class="chapter" data-level="7.2.4" data-path="paraugkopu-salidzinasana.html"><a href="paraugkopu-salidzinasana.html#atkarigu-paraugkopu-salidzinasana-ar-parametriskam-metodem"><i class="fa fa-check"></i><b>7.2.4</b> Atkarīgu paraugkopu salīdzināšana ar parametriskām metodēm</a></li>
<li class="chapter" data-level="7.2.5" data-path="paraugkopu-salidzinasana.html"><a href="paraugkopu-salidzinasana.html#vienas-paraugkopas-t-tests"><i class="fa fa-check"></i><b>7.2.5</b> Vienas paraugkopas t-tests</a></li>
<li class="chapter" data-level="7.2.6" data-path="paraugkopu-salidzinasana.html"><a href="paraugkopu-salidzinasana.html#divu-neatkarigu-paraugkopu-salidzinasana-ar-neparametriskajam-metodem"><i class="fa fa-check"></i><b>7.2.6</b> Divu neatkarīgu paraugkopu salīdzināšana ar neparametriskajām metodēm</a></li>
<li class="chapter" data-level="7.2.7" data-path="paraugkopu-salidzinasana.html"><a href="paraugkopu-salidzinasana.html#divu-atkarigu-paraugkopu-salidzinasana-ar-neparametriskajam-metodem"><i class="fa fa-check"></i><b>7.2.7</b> Divu atkarīgu paraugkopu salīdzināšana ar neparametriskajām metodēm</a></li>
<li class="chapter" data-level="7.2.8" data-path="paraugkopu-salidzinasana.html"><a href="paraugkopu-salidzinasana.html#chi2-tests-1"><i class="fa fa-check"></i><b>7.2.8</b> <span class="math inline">\(\chi^2\)</span> tests</a></li>
<li class="chapter" data-level="7.2.9" data-path="paraugkopu-salidzinasana.html"><a href="paraugkopu-salidzinasana.html#paraugkopu-grafiska-salidzinasana"><i class="fa fa-check"></i><b>7.2.9</b> Paraugkopu grafiskā salīdzināšana</a></li>
<li class="chapter" data-level="7.2.10" data-path="paraugkopu-salidzinasana.html"><a href="paraugkopu-salidzinasana.html#permutaciju-un-randomizesanas-tests-paraugkopu-salidzinasanai"><i class="fa fa-check"></i><b>7.2.10</b> Permutāciju un randomizēšanas tests paraugkopu salīdzināšanai</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="8" data-path="dispersijas-analize.html"><a href="dispersijas-analize.html"><i class="fa fa-check"></i><b>8</b> Dispersijas analīze</a><ul>
<li class="chapter" data-level="8.1" data-path="dispersijas-analize.html"><a href="dispersijas-analize.html#teoretiskais-pamatojums-3"><i class="fa fa-check"></i><b>8.1</b> Teorētiskais pamatojums</a></li>
<li class="chapter" data-level="8.2" data-path="dispersijas-analize.html"><a href="dispersijas-analize.html#dati"><i class="fa fa-check"></i><b>8.2</b> Dati</a></li>
<li class="chapter" data-level="8.3" data-path="dispersijas-analize.html"><a href="dispersijas-analize.html#dispersiju-homogenitate"><i class="fa fa-check"></i><b>8.3</b> Dispersiju homogenitāte</a></li>
<li class="chapter" data-level="8.4" data-path="dispersijas-analize.html"><a href="dispersijas-analize.html#modelu-definesana"><i class="fa fa-check"></i><b>8.4</b> Modeļu definēšana</a></li>
<li class="chapter" data-level="8.5" data-path="dispersijas-analize.html"><a href="dispersijas-analize.html#gradacijas-klasu-salidzinasana"><i class="fa fa-check"></i><b>8.5</b> Gradācijas klašu salīdzināšana</a></li>
<li class="chapter" data-level="8.6" data-path="dispersijas-analize.html"><a href="dispersijas-analize.html#rezultatu-grafiska-attelosana"><i class="fa fa-check"></i><b>8.6</b> Rezultātu grafiskā attēlošana</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="korelacijas-analize.html"><a href="korelacijas-analize.html"><i class="fa fa-check"></i><b>9</b> Korelācijas analīze</a><ul>
<li class="chapter" data-level="9.1" data-path="korelacijas-analize.html"><a href="korelacijas-analize.html#teoretiskais-pamatojums-4"><i class="fa fa-check"></i><b>9.1</b> Teorētiskais pamatojums</a></li>
<li class="chapter" data-level="9.2" data-path="korelacijas-analize.html"><a href="korelacijas-analize.html#korelacijas-analize-programma-r"><i class="fa fa-check"></i><b>9.2</b> Korelācijas analīze programmā R</a><ul>
<li class="chapter" data-level="9.2.1" data-path="korelacijas-analize.html"><a href="korelacijas-analize.html#grafiska-parbaude"><i class="fa fa-check"></i><b>9.2.1</b> Grafiskā pārbaude</a></li>
<li class="chapter" data-level="9.2.2" data-path="korelacijas-analize.html"><a href="korelacijas-analize.html#pirsona-korelacijas-analize"><i class="fa fa-check"></i><b>9.2.2</b> Pīrsona korelācijas analīze</a></li>
<li class="chapter" data-level="9.2.3" data-path="korelacijas-analize.html"><a href="korelacijas-analize.html#rangu-korelacijas-analize"><i class="fa fa-check"></i><b>9.2.3</b> Rangu korelācijas analīze</a></li>
<li class="chapter" data-level="9.2.4" data-path="korelacijas-analize.html"><a href="korelacijas-analize.html#autokorelacija"><i class="fa fa-check"></i><b>9.2.4</b> Autokorelācija</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="10" data-path="regresijas-analize.html"><a href="regresijas-analize.html"><i class="fa fa-check"></i><b>10</b> Regresijas analīze</a><ul>
<li class="chapter" data-level="10.1" data-path="regresijas-analize.html"><a href="regresijas-analize.html#teoretiskais-pamatojums-5"><i class="fa fa-check"></i><b>10.1</b> Teorētiskais pamatojums</a></li>
<li class="chapter" data-level="10.2" data-path="regresijas-analize.html"><a href="regresijas-analize.html#dati-1"><i class="fa fa-check"></i><b>10.2</b> Dati</a></li>
<li class="chapter" data-level="10.3" data-path="regresijas-analize.html"><a href="regresijas-analize.html#paru-regresija"><i class="fa fa-check"></i><b>10.3</b> Pāru regresija</a></li>
<li class="chapter" data-level="10.4" data-path="regresijas-analize.html"><a href="regresijas-analize.html#regresijas-analizes-pienemumu-parbaude"><i class="fa fa-check"></i><b>10.4</b> Regresijas analīzes pieņēmumu pārbaude</a></li>
<li class="chapter" data-level="10.5" data-path="regresijas-analize.html"><a href="regresijas-analize.html#vertibu-prognozesana"><i class="fa fa-check"></i><b>10.5</b> Vērtību prognozēšana</a></li>
<li class="chapter" data-level="10.6" data-path="regresijas-analize.html"><a href="regresijas-analize.html#daudzfaktoru-regresija"><i class="fa fa-check"></i><b>10.6</b> Daudzfaktoru regresija</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="kovariacijas-analize.html"><a href="kovariacijas-analize.html"><i class="fa fa-check"></i><b>11</b> Kovariācijas analīze</a><ul>
<li class="chapter" data-level="11.1" data-path="kovariacijas-analize.html"><a href="kovariacijas-analize.html#teoretiskais-pamatojums-6"><i class="fa fa-check"></i><b>11.1</b> Teorētiskais pamatojums</a></li>
<li class="chapter" data-level="11.2" data-path="kovariacijas-analize.html"><a href="kovariacijas-analize.html#dati-2"><i class="fa fa-check"></i><b>11.2</b> Dati</a></li>
<li class="chapter" data-level="11.3" data-path="kovariacijas-analize.html"><a href="kovariacijas-analize.html#dispersijas-analize-1"><i class="fa fa-check"></i><b>11.3</b> Dispersijas analīze</a></li>
<li class="chapter" data-level="11.4" data-path="kovariacijas-analize.html"><a href="kovariacijas-analize.html#kvantitativa-mainiga-ieklausana-modeli"><i class="fa fa-check"></i><b>11.4</b> Kvantitatīva mainīgā iekļaušana modelī</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="visparinatie-linearie-modeli.html"><a href="visparinatie-linearie-modeli.html"><i class="fa fa-check"></i><b>12</b> Vispārinātie lineārie modeļi</a><ul>
<li class="chapter" data-level="12.1" data-path="visparinatie-linearie-modeli.html"><a href="visparinatie-linearie-modeli.html#teoretiskais-pamatojums-7"><i class="fa fa-check"></i><b>12.1</b> Teorētiskais pamatojums</a></li>
<li class="chapter" data-level="12.2" data-path="visparinatie-linearie-modeli.html"><a href="visparinatie-linearie-modeli.html#dati-3"><i class="fa fa-check"></i><b>12.2</b> Dati</a></li>
<li class="chapter" data-level="12.3" data-path="visparinatie-linearie-modeli.html"><a href="visparinatie-linearie-modeli.html#puasona-regresija"><i class="fa fa-check"></i><b>12.3</b> Puasona regresija</a></li>
<li class="chapter" data-level="12.4" data-path="visparinatie-linearie-modeli.html"><a href="visparinatie-linearie-modeli.html#binara-logistiska-regresija"><i class="fa fa-check"></i><b>12.4</b> Binārā loģistiskā regresija</a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="literatura.html"><a href="literatura.html"><i class="fa fa-check"></i><b>13</b> Literatūra</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Praktiskā biometrija</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="dispersijas-analize" class="section level1">
<h1><span class="header-section-number">8. nodaļa.</span> Dispersijas analīze</h1>
<div id="teoretiskais-pamatojums-3" class="section level2">
<h2><span class="header-section-number">8.1</span> Teorētiskais pamatojums</h2>
<p>Vēl jāuzraksta!</p>
</div>
<div id="dati" class="section level2">
<h2><span class="header-section-number">8.2</span> Dati</h2>
<p>Dispersijas analīzes piemēram izmantosim datu failu <code>augi.txt</code>, kas satur informāciju par augu biomasu parauglaukumā eksperimentā, kurā pētīta barības vielu daudzuma (<code>barv</code>) un ūdens daudzuma (<code>udens</code>) ietekme. Barības vielu daudzumam ir četras iespējamās grupas: kontrole (<code>kontr</code>), papildus fosfors(<code>fosf</code>), papildus slāpeklis (<code>slap</code>) un šo abu elementu kombinācija (<code>slfo</code>). Faktoram ūdens ir divi līmeņi: kontrole (<code>norm</code>) un papildus ūdens (<code>papild</code>).</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">augi&lt;-<span class="kw">read.table</span>(<span class="dt">file=</span><span class="st">&quot;augi.txt&quot;</span>,<span class="dt">header=</span><span class="ot">TRUE</span>,<span class="dt">sep=</span><span class="st">&quot;</span><span class="ch">\t</span><span class="st">&quot;</span>,<span class="dt">dec=</span><span class="st">&quot;.&quot;</span>)
<span class="kw">str</span>(augi)</code></pre></div>
<pre><code>## &#39;data.frame&#39;:    40 obs. of  3 variables:
##  $ biomasa: num  60.8 61.3 49.6 53.8 54.1 47.6 63.7 50.3 50.9 55.7 ...
##  $ barv   : Factor w/ 4 levels &quot;fosf&quot;,&quot;kontr&quot;,..: 2 2 2 2 2 2 2 2 2 2 ...
##  $ udens  : Factor w/ 2 levels &quot;norm&quot;,&quot;papild&quot;: 1 1 1 1 1 2 2 2 2 2 ...</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">summary</span>(augi)</code></pre></div>
<pre><code>##     biomasa         barv       udens   
##  Min.   :47.60   fosf :10   norm  :20  
##  1st Qu.:55.67   kontr:10   papild:20  
##  Median :59.20   slap :10              
##  Mean   :59.66   slfo :10              
##  3rd Qu.:63.70                         
##  Max.   :74.90</code></pre>
<p>Lai gūtu sākotnējo priekštatu par augu biomasas atšķirībām starp katra no faktoriem gradācijas klasēm, var izmantot funkciju <code>tapply()</code>, kurai kā argumentus norādam kolonnu, kas satur datus, kolonnu, kas satur dalījuma līmeņus, kā arī rādītāju, kuru vēlamies aprēķināt. Šo funkciju pielietojam, lai apskatītu kāda ir vidējā aritmētiskā augu biomasa katrā no barības vielu un katrā no ūdens režīmiem.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">tapply</span>(augi$biomasa,augi$barv,mean)</code></pre></div>
<pre><code>##  fosf kontr  slap  slfo 
## 61.04 54.78 57.44 65.37</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">tapply</span>(augi$biomasa,augi$udens,mean)</code></pre></div>
<pre><code>##   norm papild 
## 59.755 59.560</code></pre>
</div>
<div id="dispersiju-homogenitate" class="section level2">
<h2><span class="header-section-number">8.3</span> Dispersiju homogenitāte</h2>
<p>Tā kā viens no dispersijas analīzes pieņēmumiem ir, ka dispersijas starp gradācijas līmeņiem ir homogēnas, tas ir, to atšķirība nav statistiski būtiska,ir jāveic dispersiju salīdzināšana. Viens no testiem, ko var izmantot, ir Bartletta tests, ko veic ar funkciju <code>bartlett.test()</code>. Šai funkcijai kā argumenti jānorāda kolonna, kas satur datus, kā arī kolonna, kas satur dalījuma līmeņus. Analīzes rezultātos parādās aprēķinātā <span class="math inline">\(K^2\)</span> vērtība, brīvības pakāpju skaits un p-vērtība.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">with</span>(augi,<span class="kw">bartlett.test</span>(biomasa,barv))</code></pre></div>
<pre><code>## 
##  Bartlett test of homogeneity of variances
## 
## data:  biomasa and barv
## Bartlett&#39;s K-squared = 4.4872, df = 3, p-value = 0.2134</code></pre>
<p><strong>Secinājums:</strong> tā kā iegūtā p-vērtība (0.2134) ir lielāka par būtiskuma līmeni (<span class="math inline">\(\alpha=0.05\)</span>), tad atšķirība starp dispersijām nav statistiski būtiska jeb dispersijas ir homogēnas.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">with</span>(augi,<span class="kw">bartlett.test</span>(biomasa,udens))</code></pre></div>
<pre><code>## 
##  Bartlett test of homogeneity of variances
## 
## data:  biomasa and udens
## Bartlett&#39;s K-squared = 1.4017, df = 1, p-value = 0.2364</code></pre>
<p><strong>Secinājums:</strong> tā kā iegūtā p-vērtība (0.2364) ir lielāka par būtiskuma līmeni (<span class="math inline">\(\alpha=0.05\)</span>), tad atšķirība starp dispersijām nav statistiski būtiska jeb dispersijas ir homogēnas.</p>
</div>
<div id="modelu-definesana" class="section level2">
<h2><span class="header-section-number">8.4</span> Modeļu definēšana</h2>
<p>Pašas dispersijas analīzes veikšanai var izmantot vairākas funkcijas, no kurām viena ir funkcija <code>aov()</code>. Šai funkcijai kā argumenti jānorāda analīzējamais mainīgais (šajā gadījumā <code>biomasa</code>), tad ir tildes zīme un viens vai vairāki ietekmējošie faktori. Ja jāpārbauda tikai faktoru atsevišķa ietekme, tad tos jāatdala ar plus zīmi, bet ja ir nepieciešams pārbaudīt arī faktoru kombinācijas ietekmi, tad faktorus var atdalīt ar zvaigznītes zīmi. Beigās jānorāda arī no kuras tabulas šos datus ņemt.</p>
<p>Dispersijas analīzē ir svarīgi, lai programma faktoru uztvertu tiešām kā faktoru. Ja gradācijas līmeņi ir nosaukti ar rakstu zīmēm, tad problēmu nav. Ja gradācijas līmeņi ir apzīmēti ar skaitļiem, tad pirms analīzes veikšanas šo mainīgo vajag pārvērst par faktoru ar funkcijas <code>as.factor()</code> palīdzību.</p>
<p>Analīzes rezultātā parādās katra faktora un atlikuma vērtību brīvības pakāpju skaits, noviržu kvadrātu summa un vidējā noviržu kvadrātu summa, atbilstošā F vērtība un p-vērtība (<code>Pr(&gt;F)</code>).</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">mod1&lt;-<span class="kw">aov</span>(biomasa~barv*udens,<span class="dt">data=</span>augi)
<span class="kw">summary</span>(mod1)</code></pre></div>
<pre><code>##             Df Sum Sq Mean Sq F value   Pr(&gt;F)    
## barv         3  632.5  210.84   9.834 9.52e-05 ***
## udens        1    0.4    0.38   0.018    0.895    
## barv:udens   3   43.7   14.56   0.679    0.571    
## Residuals   32  686.1   21.44                     
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p><strong>Secinājums:</strong> faktora barības vielu daudzums ietekme uz augu biomasu ir statistiski būtiska, jo iegūtā p-vērtība ir mazāka par noteikto būtiskuma līmeni (<span class="math inline">\(\alpha=0.05\)</span>), bet faktora ūdens un abu faktoru kombinācijas ietekme nav statistiski būtiska, jo iegūtās p-vērtības ir lielākas par būtiskuma līmeni.</p>
<p>Tā kā faktora ūdens un faktoru kombinācijas ietekme nav būtiska, tad varam izveidot arī vienkāršāku modeli, kurā ir atstāts tikai faktors barības vielu daudzums. Arī šajā modelī barības vielu daudzuma ietekme ir būtiska.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">mod2&lt;-<span class="kw">aov</span>(biomasa~barv,<span class="dt">data=</span>augi)
<span class="kw">summary</span>(mod2)</code></pre></div>
<pre><code>##             Df Sum Sq Mean Sq F value   Pr(&gt;F)    
## barv         3  632.5  210.84   10.39 4.54e-05 ***
## Residuals   36  730.1   20.28                     
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
</div>
<div id="gradacijas-klasu-salidzinasana" class="section level2">
<h2><span class="header-section-number">8.5</span> Gradācijas klašu salīdzināšana</h2>
<p>Konstatējot kāda faktora būtisku ietekmi, var veikt tā saucamo post-hoc testu, tas ir, salīdzināt gradācijas klases savā starpā. Viena no funkcijām šādam testam ir <code>TukeyHSD</code>. Šai funkcijai kā argumenti jānorāda piemērotās dispersijas analīzes modelis, kā arī pēdiņās jānorāda faktora nosaukums, kura gradācijas klases savā starpā vēlas salīdzināt. Analīzes rezultātos iegūst vidējo aritmētisko starpību starp katrām divām gradācijas klasēm, šo vidējo aritmētisko starpības ticamības intervālu un atbilstošo p-vērtību.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">TukeyHSD</span>(mod2,<span class="st">&quot;barv&quot;</span>)</code></pre></div>
<pre><code>##   Tukey multiple comparisons of means
##     95% family-wise confidence level
## 
## Fit: aov(formula = biomasa ~ barv, data = augi)
## 
## $barv
##             diff       lwr        upr     p adj
## kontr-fosf -6.26 -11.68427 -0.8357301 0.0183777
## slap-fosf  -3.60  -9.02427  1.8242699 0.2958204
## slfo-fosf   4.33  -1.09427  9.7542699 0.1570183
## slap-kontr  2.66  -2.76427  8.0842699 0.5561038
## slfo-kontr 10.59   5.16573 16.0142699 0.0000391
## slfo-slap   7.93   2.50573 13.3542699 0.0019671</code></pre>
<p><strong>Secinājums:</strong> statistiski būtiska atšķirība pastāv starp gradācijas klasēm kontrole-fosfors, kontrole-fosfors/slapeklis, kā arī slāpeklis-fosfors/slapeklis, jo atbilstošās p-vērtības ir mazākas par būtiskuma līmeni. Pārējos gadījumos atšķirības starp gradācijas klašu vidējiem aritmētiskajiem nav statistiski būtiska, jo iegūtās p-vērtības ir lielākas par noteikto būtiskuma līmeni.</p>
</div>
<div id="rezultatu-grafiska-attelosana" class="section level2">
<h2><span class="header-section-number">8.6</span> Rezultātu grafiskā attēlošana</h2>
<p>Dispersijas analīzes rezultātu grafiskai attēlošanai var izmantot vairākus grafiku veidus, piemēram, box-plot grafiku apvienojumu, kur katrai gradācijas klasei ir savs mazais box-plot attēls (<a href="dispersijas-analize.html#fig:anov-007">8.1</a> attēls).</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">boxplot</span>(augi$biomasa~augi$barv)</code></pre></div>
<div class="figure"><span id="fig:anov-007"></span>
<img src="PBB_gramata_files/figure-html/anov-007-1.png" alt="Gradācijas klašu box-plot attēls"  />
<p class="caption">
Figure 8.1: Gradācijas klašu box-plot attēls
</p>
</div>
<p>Vēl viens variants ir izmantot funkciju <code>plotmeans()</code> no paketes <code>gplots</code>. Šī funkcija izveido grafiku, kurā attēlots katras gradācijas klases vidējais aritmētiskais un tā ticamības intervāls (<a href="dispersijas-analize.html#fig:anov-008">8.2</a> attēls). Kā papildus arguments izmantots <code>connect=FALSE</code>, lai vidējie aritmētiskie netiktu savā starpā automātiski savienoti.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(gplots)</code></pre></div>
<pre><code>## 
## Attaching package: &#39;gplots&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:plotrix&#39;:
## 
##     plotCI</code></pre>
<pre><code>## The following object is masked from &#39;package:stats&#39;:
## 
##     lowess</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">plotmeans</span>(augi$biomasa~augi$barv,<span class="dt">connect=</span><span class="ot">FALSE</span>,<span class="dt">xlab=</span><span class="st">&quot;baribas vielas&quot;</span>)</code></pre></div>
<div class="figure"><span id="fig:anov-008"></span>
<img src="PBB_gramata_files/figure-html/anov-008-1.png" alt="Gradācijas klašu vidējo aritmētisko attēls"  />
<p class="caption">
Figure 8.2: Gradācijas klašu vidējo aritmētisko attēls
</p>
</div>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="paraugkopu-salidzinasana.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="korelacijas-analize.html" class="navigation navigation-next " aria-label="Next page""><i class="fa fa-angle-right"></i></a>

<script src="libs/gitbook-2.6.7/js/app.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"facebook": true,
"twitter": true,
"google": false,
"weibo": false,
"instapper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"download": ["PBB_gramata.pdf", "PBB_gramata.epub", "PBB_gramata.mobi"],
"toc": {
"collapse": "subsection"
}
});
});
</script>


</body>

</html>
